apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: helloworld
  name: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      run: helloworld
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: helloworld
        app.kubernetes.io/instance: poc-ci
    spec:
      containers:
      - name: helloworld
        image: gcr.io/sandbox-latam-xp/helloworld-app:latest
        resources: {}
        command:
        - java
        args:
        - -cp
        - /opt/helloworld/helloworld-1.0-SNAPSHOT.jar:/opt/helloworld/mysql-connector-java-8.0.17.jar
        - com.latamxp.app.App
        env:
        - name: MYSQL_DATABASE
          value: db
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_USER
          value: user
        - name: MYSQL_PASS
          value: password
        - name: GIT_COMMIT
          value: latest
status: {}
