apiVersion: v1
kind: Service
metadata:
  labels:
    run: helloworld
  name: helloworld
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    run: helloworld
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
